project-safari/zebra

.github/workflows/test.yml
=> zebra: add test github action

.github/workflows/lint.yml, .gitignore, .golangcilint.yaml, Makefile, dc/dc.go, dc/dc_test.go, doc.go, resource.go, resource_test.go
=> zebra: fix lint issues and add lint action

README.md
=> zebra: add badges to readme

README.md, dc/dc.go, dc/dc_test.go, resource.go, resource_test.go
=> added struct and function comments

.github/workflows/dco.yml
enforce: https://github.com/apps/dco
=> zebra: enable DCO action

.github/workflows/license.yml, .github/workflows/loc.yaml, .github/workflows/stale.yml
* license check to verify all dependent component licenses are
compatible
* lines of code action to give insight into loc for PR, main and
releases
* stale issue and PR checker that closes stale issues periodically
=> add github actions for best OSS practices

resource.go, resource_test.go, store/store.go, store/store_test.go
1. added StoredResource struct in resource.go
2. functions for initializing, clearing, and deleting store in store.go
3. functions for loading, storing, and deleting objects in store.go
4. tests for store.go in store_test.go
Fixes #17 
=> added store functions

query/query.go, query/query_test.go, resource.go, resource_test.go
1. added GetName() and GetLabels() functions to Resource interface.
2. implemented GetName() for BaseResource and NamedResource, implemented GetLabels() for BaseResource.
3. added filter functions for UUID, type, type and name, and label in query.go.
4. test query functionality in query_test.go.
Fixes #18.
=> query store functions

Makefile
=> check licenses for go dependencies

.github/workflows/bin.yml
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>
=> upload artifacts on releases

.golangcilint.yaml, api/api.go, resmap.go
=> disable varnamelen linter, its useless

.github/workflows/codeql.yml, .github/workflows/test.yml
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>
=> fix github workflows

.github/workflows/test.yml
=> use codecov v3 action

go.mod, go.sum, helpers.go, helpers_test.go
returns base resource given type and labels, with unique UUID.
=> added helper function to return base resource

cmd/server/main.go, server.json
make auth key configuration as a string and change the example in the
server.json accordingly.
=> fix authKey config

cmd/server/api.go, cmd/server/api_test.go, cmd/server/main.go
PUT --> POST
registered handlers for POST handlePost() and DELETE handleDelete()
added logging for handleQuery(), handlePost(), and handleDelete()
added tests for internal functions
Fixes #76
=> registered POST and DELTE

cmd/herd/pkg/address.go, cmd/herd/pkg/herd_test.go, cmd/herd/pkg/vcenter.go, compute/compute.go, dc/dc.go, network/network.go
* fix ip assignment
* fix type assignment
* fix credential assignment
* add test cases to make sure all generated resources are valid and are
of the right type
=> herd: fix resource generation

cmd/server/main.go
=> zebra: login should use POST method

auth/jwt.go, auth/jwt_test.go, auth/user.go, cmd/server/login.go, cmd/server/login_test.go, cmd/server/refresh.go, cmd/server/refresh_test.go, cmd/server/register.go, cmd/server/register_test.go
=> Created User Registration Api

auth/jwt.go, auth/user.go, auth/user_test.go, cmd/server/api.go, cmd/server/api_test.go, cmd/server/auth.go, cmd/server/auth_test.go, cmd/server/ctx.go, cmd/server/json.go, cmd/server/json_test.go, cmd/server/labels.go, cmd/server/labels_test.go, cmd/server/login.go, cmd/server/login_test.go, cmd/server/main.go, cmd/server/refresh.go, cmd/server/refresh_test.go, cmd/server/register.go, cmd/server/register_test.go, cmd/server/routes.go, cmd/server/routes_test.go, cmd/server/setup.go, cmd/server/setup_test.go, cmd/server/types.go, cmd/server/types_test.go
=> auth: add authentication to zebra

.gitignore, Makefile, auth/rsa.go, auth/rsa_test.go, cmd/client/client.go, cmd/client/client_test.go, cmd/client/config.go, cmd/client/config_test.go, cmd/client/main.go, cmd/client/main_test.go, cmd/client/root.go, cmd/server/login_test.go, cmd/server/register.go, cmd/server/register_test.go, cmd/server/setup_test.go, simulator/gen_certs.sh, simulator/key_test.go, simulator/zebra-simulator.json
=> zebra config and auth client

cmd/client/client_test.go, cmd/client/config.go, go.mod, helpers.go, lease/lease.go, lease/lease_test.go
Note: status is right now in zebra package -- future commit will move it to its own package
=> lease object

cmd/server/login.go
```
{
"email": "admin@zebra.project-safari.io",
"jwt": "eyJhbG...",
"role": {
"name": "admin",
"privileges": [
":c,r,u,d"
]
}
}
```
=> login: include user role and email

cmd/server/refresh.go, cmd/server/refresh_test.go
=> refresh: fix error code to unauthorized

cmd/server/api.go, cmd/server/api_test.go
=> GET now allows empty body

cmd/server/login.go
=> add name to login response

cmd/server/api.go, cmd/server/api_test.go
Signed-off-by: Charles Lovett <calovett35@gmail.com>
=> Modified Delete API to just need the resource's id as a payload
